configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bounty-lab%2Fbountylab-6f2eb0f8753cb2caae426cbddda7c5c1515f8d879adfd63df9e3ba3c95334ffd.yml
openapi_spec_hash: 89dd532d92d61a2eda7587df970a18bc
config_hash: 5afd906274ee39ac1a9ea36ea4ea772a
